# Generated by Django 3.2.4 on 2021-07-14 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_customer_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='potency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.potency'),
        ),
    ]
